In [1]:
#  Use Pandas to clean and format your data set(s)

#  Create a Jupyter Notebook describing the data exploration and cleanup process

#  Create a Jupyter Notebook illustrating the final data analysis

#  Use Matplotlib to create a total of 6-8 visualizations of your data (ideally, at least 2 per "question" you ask of your data)

#  Save PNG images of your visualizations to distribute to the class and instructional team, and for inclusion in your presentation

#  Optionally, use at least one API, if you can find an API with data pertinent to your primary research questions

#  Create a write-up summarizing your major findings. This should include a heading for each "question" you asked of your data, and under each heading, a short description of what you found and any relevant plots.

In [48]:
# import packages 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [58]:
# read data as csv
file_bushfire = '../DISNEY-DONUT-PROJECT/Resources/bushfire_data.csv'
bushfire_df = pd.read_csv(file_bushfire)

In [59]:
bushfire_df.head()

,year,description,state,area burned ha,area burned acres,fatalities,homes destroyed,other buildings destroyed,cattle sheep,cattle general,approx value loss,approx value loss (current $)
0,1851,Black Thursday bushfires,Victoria,5000000.0,12000000.0,12.0,0,0.0,1000000.0,2000.0,NaN,NaN
1,1895,Upper Blue Mountains fires,New South Wales,150.0,370.0,0.0,12,1.0,NaN,NaN,NaN,NaN
2,1898,Red Tuesday bushfires,Victoria,260000.0,640000.0,12.0,0,2000.0,NaN,NaN,NaN,NaN
3,1926,1926 bushfires,Victoria,390000.0,960000.0,60.0,1000,0.0,NaN,NaN,NaN,NaN
4,1939,Black Friday bushfires,Victoria,2000000.0,4900000.0,71.0,3700,0.0,NaN,NaN,NaN,NaN

In [60]:
# check data that has number is a 'float', i.e. every variable except 'year', 'description', 'state' and 'series ID' should be a float
bushfire_df.dtypes

year                               int64
description                       object
state                             object
area burned ha                   float64
area burned acres                float64
fatalities                       float64
homes destroyed                   object
other buildings destroyed        float64
cattle sheep                     float64
cattle general                   float64
approx value loss                 object
approx value loss (current $)    float64
dtype: object

In [61]:
# check timeseries 
bushfire_df.groupby('state').count()['year'].sort_values()

state
West                             1
Australian Capital Territory     2
Queensland                       3
Northern Territory               5
South Australia                 10
Tasmania                        14
Western Australia               18
Victoria                        20
New South Wales                 28
Name: year, dtype: int64

In [62]:
# proxy for the severity of bushfire is 'area burned ha'
# check na's in these two variables 

bushfire_df['area burned ha'].isnull().sum()

4

In [63]:
yearly_fires = bushfire_df.groupby('year').sum()
yearly_fires

,area burned ha,area burned acres,fatalities,other buildings destroyed,cattle sheep,cattle general,approx value loss (current $)
year,,,,,,,
1851,5000000.0,12000000.0,12.0,0.0,1000000.0,2000.000000,0.000000e+00
1895,150.0,370.0,0.0,1.0,0.0,0.000000,0.000000e+00
1898,260000.0,640000.0,12.0,2000.0,0.0,0.000000,0.000000e+00
1926,390000.0,960000.0,60.0,0.0,0.0,0.000000,0.000000e+00
1939,2000000.0,4900000.0,71.0,0.0,0.0,0.000000,0.000000e+00
1944,1000000.0,2500000.0,22.0,0.0,0.0,0.000000,0.000000e+00
1952,4000000.0,9900000.0,11.0,0.0,0.0,0.000000,0.000000e+00
1955,160000.0,395000.0,2.0,0.0,0.0,0.000000,0.000000e+00
1957,2000000.0,0.0,4.0,14.0,0.0,0.000000,7.351586e+07
1961,1800000.0,4400000.0,0.0,0.0,0.0,0.000000,0.000000e+00
1962,0.0,0.0,32.0,0.0,0.0,0.000000,0.000000e+00
1965,566000.0,1400000.0,3.0,60.0,0.0,4000.000000,0.000000e+00
1967,264000.0,650000.0,62.0,128.0,0.0,62000.000000,1.850400e+08
1968,41500000.0,99000000.0,14.0,5.0,0.0,0.000000,3.833702e+07
1969,250000.0,0.0,22.0,21.0,0.0,12000.000000,0.000000e+00
1970,45000000.0,110000000.0,0.0,0.0,0.0,0.000000,0.000000e+00
1975,101800000.0,248000000.0,6.0,0.0,6850.0,57095.000000,3.855000e+07
1977,157000.0,380000.0,6.0,340.0,0.0,0.000000,5.407013e+07
1978,114000.0,280000.0,2.0,6.0,0.0,0.000000,0.000000e+00
1979,50000.0,0.0,5.0,0.0,0.0,0.000000,0.000000e+00
1980,1008000.0,2500000.0,5.0,1.0,0.0,0.000000,5.971996e+07
1982,5000.0,0.0,1.0,46.0,0.0,3000.000000,0.000000e+00
1983,478000.0,1030000.0,78.0,0.0,0.0,19300.000000,6.111100e+08
1984,500000.0,1200000.0,0.0,0.0,0.0,5714.285714,2.261498e+07
1985,3050800.0,7526000.0,8.0,0.0,0.0,34285.714287,9.992806e+07
1991,0.0,0.0,2.0,0.0,0.0,0.000000,2.368259e+07
1993,2400.0,0.0,0.0,0.0,0.0,0.000000,0.000000e+00
1994,805000.0,990000.0,4.0,0.0,0.0,0.000000,2.213266e+08
1997,933900.0,1083990.0,8.0,0.0,0.0,0.000000,6.734378e+07
1998,780.0,0.0,5.0,0.0,0.0,0.000000,0.000000e+00
2001,753314.0,1861480.0,0.0,0.0,0.0,0.000000,1.084219e+08
2002,38000000.0,94000000.0,0.0,0.0,0.0,0.000000,0.000000e+00
2003,3570000.0,8800000.0,6.0,213.0,0.0,0.000000,5.369067e+08
2005,290337.0,722070.0,13.0,360.0,63243.0,1021.000000,7.085375e+07
2006,4042182.0,6536000.0,12.0,74.0,100.0,0.000000,6.851303e+07
2007,147000.0,359000.0,4.0,0.0,0.0,0.000000,0.000000e+00
2008,18500.0,0.0,0.0,0.0,0.0,0.000000,0.000000e+00
2009,450000.0,1100000.0,173.0,2000.0,0.0,0.000000,1.335984e+09
2010,10700.0,0.0,0.0,0.0,0.0,0.000000,0.000000e+00
2011,66520.0,0.0,0.0,1.0,0.0,0.000000,1.041412e+08
2012,800000.0,2000000.0,0.0,0.0,0.0,0.000000,0.000000e+00
2013,194000.0,429000.0,2.0,328.0,0.0,0.000000,3.455362e+08
2014,650.0,0.0,1.0,0.0,0.0,0.000000,1.651750e+07
2015,414739.0,1020190.0,6.0,145.0,0.0,0.000000,0.000000e+00
2016,69165.0,170910.0,2.0,0.0,0.0,0.000000,0.000000e+00
2017,52000.0,130000.0,0.0,0.0,0.0,0.000000,0.000000e+00
2019,23419.0,57870.0,0.0,57.0,0.0,0.000000,0.000000e+00
2020,19112464.0,47202660.0,34.0,6000.0,0.0,0.000000,2.300000e+09

In [66]:
# create dataframe that does not have any nulls for 'approx value loss'
value_loss_df = bushfire_df.dropna(subset =  ['area burned ha', 'approx value loss'])
value_loss_df.isnull().sum()

year                              0
description                       0
state                             0
area burned ha                    0
area burned acres                10
fatalities                        8
homes destroyed                   6
other buildings destroyed         8
cattle sheep                     38
cattle general                   32
approx value loss                 0
approx value loss (current $)     0
dtype: int64

In [69]:
value_loss_df

,year,description,state,area burned ha,area burned acres,fatalities,homes destroyed,other buildings destroyed,cattle sheep,cattle general,approx value loss,approx value loss (current $)
9,1957,"1957 Grose Valley bushfire, Blue Mountains",New South Wales,2000000.0,NaN,4.0,158,12.000000,NaN,NaN,"£1,000,000",3.699481e+07
15,1967,Black Tuesday bushfires,Tasmania,264000.0,650000.0,62.0,1400,128.000000,NaN,62000.000000,14000000,1.850400e+08
17,1968,1968 Blue Mountains Bushfire,New South Wales,1500000.0,NaN,14.0,150,5.000000,NaN,NaN,3000000,3.833702e+07
20,1975,1974-75 Australian bushfire season,New South Wales,4500000.0,11000000.0,6.0,NaN,NaN,NaN,NaN,221021.611,1.704077e+06
21,1975,1974-75 Australian bushfire season,Northern Territory,45000000.0,110000000.0,NaN,NaN,NaN,NaN,57000.000000,2210216.11,1.704077e+07
22,1975,1974-75 Australian bushfire season,Queensland,7300000.0,18000000.0,NaN,NaN,NaN,6850.0,95.000000,358546.169,2.764391e+06
23,1975,1974-75 Australian bushfire season,South Australia,16000000.0,37000000.0,NaN,NaN,NaN,NaN,NaN,785854.6169,6.058939e+06
24,1975,1974-75 Australian bushfire season,Western Australia,29000000.0,72000000.0,NaN,NaN,NaN,NaN,NaN,1424361.493,1.098183e+07
25,1977,Western Districts bushfires,Victoria,103000.0,250000.0,4.0,116,340.000000,NaN,NaN,9000000,5.407013e+07
30,1980,Mt Lofty Ranges,South Australia,8000.0,NaN,NaN,51,1.000000,NaN,NaN,13000000,5.971996e+07
32,1983,Grays Point bushfire,New South Wales,60000.0,NaN,3.0,0,0.000000,NaN,NaN,3000000,1.024207e+07
33,1983,Ash Wednesday bushfires,South Australia,418000.0,1030000.0,75.0,". 2,400",0.000000,NaN,19300.000000,176000000,6.008679e+08
34,1984,1984 Western New South Wales grasslands bushfires,New South Wales,500000.0,1200000.0,0.0,0,0.000000,NaN,5714.285714,7381889.764,2.261498e+07
35,1985,1985 Cobar bushfire,New South Wales,516000.0,1280000.0,0.0,0,0.000000,NaN,5897.142857,7618110.236,2.333866e+07
36,1985,1984 - 85 New South Wales bushfires,New South Wales,2484000.0,6120000.0,5.0,0,0.000000,NaN,28388.571430,25000000,7.658940e+07
40,1994,Beerburrum State Forest and urban fires along ...,Queensland,5000.0,NaN,NaN,23,NaN,NaN,NaN,59100000,1.112725e+08
41,1994,1994 Eastern seaboard fires,New South Wales,800000.0,990000.0,4.0,225,0.000000,NaN,NaN,59000000,1.100540e+08
43,1997,Dandenongs bushfire,Victoria,400.0,990.0,3.0,41,0.000000,NaN,NaN,29000000,5.007615e+07
45,1997,Menai bushfire,New South Wales,500000.0,NaN,1.0,11,0.000000,NaN,NaN,10000000,1.726764e+07
48,2001,Black Christmas bushfires,New South Wales,753314.0,1861480.0,0.0,121,0.000000,NaN,NaN,69000000,1.084219e+08
50,2003,2003 Canberra bushfires,Australian Capital Territory,160000.0,400000.0,4.0,500,0.000000,NaN,NaN,350000000,5.191087e+08
51,2003,2003 Eastern Victorian alpine bushfires,Victoria,1300000.0,3200000.0,0.0,41,213.000000,NaN,NaN,12000000,1.779801e+07
53,2005,2005 Eyre Peninsula bushfire,South Australia,77964.0,192650.0,9.0,93,0.000000,NaN,NaN,27700000,3.917463e+07
55,2005,2005 Victorian bushfires,Victoria,160000.0,400000.0,4.0,57,359.000000,63243.0,1021.000000,22400000,3.167912e+07
61,2006,2006–07 Australian bushfire season,Tasmania,15300.0,NaN,1.0,26,28.000000,NaN,NaN,50000000,6.851303e+07
68,2009,Black Saturday bushfires,Victoria,450000.0,1100000.0,173.0,2029,2000.000000,NaN,NaN,1070000000,1.335984e+09
72,2011,"Perth Hills, Western Australia 2011",Western Australia,1540.0,NaN,NaN,110,NaN,NaN,NaN,35000000,4.141980e+07
73,2011,Augusta and Margaret River fires,Western Australia,58550.0,NaN,NaN,246,1.000000,NaN,NaN,53000000,6.272141e+07
78,2013,Tasmanian bushfires,Tasmania,20000.0,49000.0,1.0,0,170.000000,NaN,NaN,87100000,9.851457e+07
79,2013,Warrumbungle bushfire,New South Wales,54000.0,130000.0,0.0,53,118.000000,NaN,NaN,35000000,3.958680e+07
80,2013,2013 New South Wales bushfires,New South Wales,120000.0,250000.0,1.0,208,40.000000,NaN,NaN,183400000,2.074348e+08
82,2014,"Preth Hills, Western Australia 2014",West,650.0,NaN,1.0,NaN,NaN,NaN,NaN,15000000,1.651750e+07
93,2020,2019–20 Australian bushfire season (Black Summer),Northern Territory,6800000.0,16800000.0,0.0,5,2134.732602,NaN,NaN,818314164,8.183142e+08
94,2020,2019–20 Australian bushfire season (Black Summer),New South Wales,5500000.0,13600000.0,26.0,2448,1726.621957,NaN,NaN,661871750.3,6.618718e+08
95,2020,2019–20 Australian bushfire season (Black Summer),Queensland,2500000.0,6180000.0,0.0,48,784.828162,NaN,NaN,300850795.6,3.008508e+08
96,2020,2019–20 Australian bushfire season (Black Summer),Western Australia,2200000.0,5400000.0,0.0,1,690.648783,NaN,NaN,264748700.1,2.647487e+08
97,2020,2019–20 Australian bushfire season (Black Summer),Victoria,1500000.0,3710000.0,5.0,396,470.896897,NaN,NaN,180510477.4,1.805105e+08
98,2020,2019–20 Australian bushfire season (Black Summer),South Australia,490000.0,1210000.0,3.0,151,153.826320,NaN,NaN,58966755.93,5.896676e+07
99,2020,2019–20 Australian bushfire season (Black Summer),Australian Capital Territory,86464.0,213660.0,0.0,0,27.143753,NaN,NaN,10405105.28,1.040511e+07
100,2020,2019–20 Australian bushfire season (Black Summer),Tasmania,36000.0,89000.0,0.0,2,11.301526,NaN,NaN,4332251.456,4.332251e+06

In [71]:
sum_loss = value_loss_df.groupby('year').sum()
sum_loss

,area burned ha,area burned acres,fatalities,other buildings destroyed,cattle sheep,cattle general,approx value loss (current $)
year,,,,,,,
1957,2000000.0,0.0,4.0,12.0,0.0,0.000000,3.699481e+07
1967,264000.0,650000.0,62.0,128.0,0.0,62000.000000,1.850400e+08
1968,1500000.0,0.0,14.0,5.0,0.0,0.000000,3.833702e+07
1975,101800000.0,248000000.0,6.0,0.0,6850.0,57095.000000,3.855000e+07
1977,103000.0,250000.0,4.0,340.0,0.0,0.000000,5.407013e+07
1980,8000.0,0.0,0.0,1.0,0.0,0.000000,5.971996e+07
1983,478000.0,1030000.0,78.0,0.0,0.0,19300.000000,6.111100e+08
1984,500000.0,1200000.0,0.0,0.0,0.0,5714.285714,2.261498e+07
1985,3000000.0,7400000.0,5.0,0.0,0.0,34285.714287,9.992806e+07
1994,805000.0,990000.0,4.0,0.0,0.0,0.000000,2.213266e+08
1997,500400.0,990.0,4.0,0.0,0.0,0.000000,6.734378e+07
2001,753314.0,1861480.0,0.0,0.0,0.0,0.000000,1.084219e+08
2003,1460000.0,3600000.0,4.0,213.0,0.0,0.000000,5.369067e+08
2005,237964.0,592650.0,13.0,359.0,63243.0,1021.000000,7.085375e+07
2006,15300.0,0.0,1.0,28.0,0.0,0.000000,6.851303e+07
2009,450000.0,1100000.0,173.0,2000.0,0.0,0.000000,1.335984e+09
2011,60090.0,0.0,0.0,1.0,0.0,0.000000,1.041412e+08
2013,194000.0,429000.0,2.0,328.0,0.0,0.000000,3.455362e+08
2014,650.0,0.0,1.0,0.0,0.0,0.000000,1.651750e+07
2020,19112464.0,47202660.0,34.0,6000.0,0.0,0.000000,2.300000e+09